import type { Metadata } from "next";
import { LegalList, LegalPage, LegalSection } from "@/app/components/LegalPage";

export const metadata: Metadata = { title: "Terms of Service - Votrio", description: "Terms governing access to and use of Votrio." };

export default function TermsPage() {
  return <LegalPage eyebrow="Legal" title="Terms of Service" summary="These terms establish the rules for creating an account, scanning code, using reports, and accessing Votrio.">
    <LegalSection title="1. Agreement and eligibility"><p>By accessing Votrio, you agree to these Terms and the Acceptable Use Policy. You must be legally capable of entering a binding agreement. If you use Votrio for an organization, you represent that you are authorized to accept these Terms for it.</p></LegalSection>
    <LegalSection title="2. Accounts"><p>Provide accurate information, protect your credentials, and promptly notify us of suspected unauthorized access. You are responsible for activity under your account and for ensuring that team members have appropriate access.</p></LegalSection>
    <LegalSection title="3. Your code and authorization"><p>You retain ownership of repositories, files, and other content you submit. You grant Votrio a limited license to access, process, transmit to disclosed service providers, and display that content only as needed to operate, secure, and improve the requested service. You represent that you own the content or have permission to scan and process it.</p></LegalSection>
    <LegalSection title="4. Reports and generated output"><p>Subject to third-party rights and applicable law, you may use reports and remediation suggestions generated for you. Security findings are automated indicators, not a guarantee that code is secure, compliant, or free of vulnerabilities. You must review changes before deploying them.</p></LegalSection>
    <LegalSection title="5. Acceptable use"><p>You must comply with the <a href="/acceptable-use" className="text-foreground underline">Acceptable Use Policy</a>. You may not use Votrio to attack systems, distribute malware, access code without authorization, evade limits, or interfere with the service.</p></LegalSection>
    <LegalSection title="6. Plans and payment"><p>The current guest scan may be offered without charge. If Votrio introduces a paid plan, the price, billing interval, taxes, renewal terms, and cancellation process will be disclosed before you purchase. You authorize applicable charges when you select a paid plan. Except where law requires otherwise, fees already incurred are non-refundable.</p></LegalSection>
    <LegalSection title="7. Third-party services"><p>Votrio interoperates with services such as GitHub, Supabase, Mistral AI, and Resend. Their terms may also apply. We are not responsible for third-party services outside our control.</p></LegalSection>
    <LegalSection title="8. Availability and changes"><p>We may modify, suspend, or discontinue features, impose reasonable usage limits, or perform maintenance. We do not promise uninterrupted or error-free availability.</p></LegalSection>
    <LegalSection title="9. Disclaimers"><p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, VOTRIO IS PROVIDED “AS IS” AND “AS AVAILABLE,” WITHOUT WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, ACCURACY, OR SECURITY. AUTOMATED ANALYSIS MAY MISS VULNERABILITIES OR PRODUCE FALSE POSITIVES.</p></LegalSection>
    <LegalSection title="10. Limitation of liability"><p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, VOTRIO AND ITS OPERATORS WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR LOSS OF DATA, PROFITS, REVENUE, GOODWILL, OR BUSINESS. TOTAL LIABILITY FOR ANY CLAIM WILL NOT EXCEED THE GREATER OF US$100 OR THE AMOUNT YOU PAID VOTRIO DURING THE 12 MONTHS BEFORE THE EVENT GIVING RISE TO THE CLAIM. Some jurisdictions do not allow certain limitations, so they may not apply to you.</p></LegalSection>
    <LegalSection title="11. Indemnity"><p>To the extent permitted by law, you will defend and indemnify Votrio and its operators from claims arising from your content, your unlawful or unauthorized use, or your violation of these Terms.</p></LegalSection>
    <LegalSection title="12. Termination"><p>You may stop using Votrio or delete your account at any time. We may suspend or terminate access for material violations, security risks, legal requirements, nonpayment, or conduct that harms Votrio or others. Provisions that by their nature should survive termination will survive.</p></LegalSection>
    <LegalSection title="13. Governing law and disputes"><p>These Terms are governed by the laws applicable in the jurisdiction where Votrio’s operator is established, without regard to conflict-of-law principles. Courts with jurisdiction over that operator will have exclusive jurisdiction, unless consumer-protection law requires another forum. Nothing here limits rights that cannot lawfully be waived.</p></LegalSection>
    <LegalSection title="14. General"><LegalList><li>These Terms, the Privacy Policy, Cookie Notice, and Acceptable Use Policy form the agreement governing Votrio.</li><li>If a provision is unenforceable, the remaining provisions remain effective.</li><li>Failure to enforce a provision is not a waiver.</li><li>You may not transfer these Terms without consent; Votrio may transfer them as part of a reorganization or sale.</li></LegalList></LegalSection>
  </LegalPage>;
}
